### ISSUE TITLE
assignment6 - saagarjha-08

### ISSUE THREAD

**Issue by degrigis** [zxybazh/IMP-DFA-test-suite#22]
If I remember correctly this is not allowed, right?

x.1 := y.1;

**Comment by sidsenkumar11** [comment]
Yeah, I guess this should also be removed from the test cases. Not sure why my code doesn't break on these; maybe because I'm using the professor's parser? Anyway feel free to make a PR if you want to remove it

**Comment by degrigis** [comment]
I'm using professor's parser too...I think it's safe to remove, will submit a PR :-)
