### ISSUE TITLE
YanjuChen testcases

### ISSUE THREAD

**Issue by Lukas-Dresel** [zxybazh/IMP-DFA-test-suite#3]
Here's a couple things I noticed about the new fixed versions. 

### YanjuChen-03
Node 6 represents the top of the if statement and therefore should be `Even`, not `Top`.

### YanjuChen-08
At node 60 the result should be `Top`, because `d` is `Top`

### YanjuChen-09
The last line has a duplicate node 50.

### YanjuChen-11 
The columns for c and y seem incorrect.

**Comment by chyanju** [comment]
I get little confused:
`d:={0,1}`
`z:=d+d`
If using the rules `Top+Top=Top` then `z=Top`. But by eyeballing, `z:=d+d` can also be `z:=d*2`, and no matter what the value of `d` is, `z` will always end up with `z=Even`. 

Maybe I'm missing something in the lecture, but how do we deal with this case? I see similar expressions in other files.

**Comment by zxybazh** [comment]
I have talked with @chyanju and will fix this soon.
